name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

# 🔑 dá permissão de escrita ao GITHUB_TOKEN
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog since last tag
        id: changelog
        shell: bash
        run: |
          last_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$last_tag" ]; then
            notes=$(git log --pretty=format:'- %s')
          else
            notes=$(git log $last_tag..HEAD --pretty=format:'- %s')
          fi
          notes="${notes//$'\n'/%0A}"
          echo "notes=$notes" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## Mudanças
            ${{ steps.changelog.outputs.notes }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          token: ${{ secrets.GITHUB_TOKEN }}   # 👈 explícito
